# Generated by Django 5.1.3 on 2026-01-16 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sutra_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID Medida (SUTRA)"
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="Número")),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Título"),
                ),
                (
                    "filing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Radicación"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Radicado", max_length=100, verbose_name="Estado"
                    ),
                ),
                ("sutra_url", models.URLField(verbose_name="Enlace Oficial")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("is_alerted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Medida Legislativa",
                "verbose_name_plural": "Medidas Legislativas",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(max_length=100, verbose_name="Palabra Clave"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Término de Búsqueda",
                "verbose_name_plural": "Términos de Búsqueda",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Sistema Activo"),
                ),
                (
                    "high_freq_start",
                    models.TimeField(
                        default="08:00", verbose_name="Inicio Horario Intensivo"
                    ),
                ),
                (
                    "high_freq_end",
                    models.TimeField(
                        default="21:00", verbose_name="Fin Horario Intensivo"
                    ),
                ),
                (
                    "high_freq_interval",
                    models.IntegerField(default=5, verbose_name="Minutos (Intensivo)"),
                ),
                (
                    "low_freq_interval",
                    models.IntegerField(default=60, verbose_name="Minutos (Pasivo)"),
                ),
                (
                    "active_days",
                    models.CharField(
                        default="0,1,2,3,4",
                        max_length=20,
                        verbose_name="Días Laborables (0=Lun, 6=Dom)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Avanzada",
                "verbose_name_plural": "Configuración Avanzada",
            },
        ),
        migrations.CreateModel(
            name="BillEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.bill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "discord_webhook",
                    models.URLField(
                        blank=True, null=True, verbose_name="Webhook Discord"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
