# Generated by Django 5.1.3 on 2026-01-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="commission",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Comisión"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="active_days",
            field=models.CharField(
                default="0,1,2,3,4", max_length=20, verbose_name="Días Laborables"
            ),
        ),
    ]
