# Generated by Django 5.1.3 on 2026-01-16 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bill_commission_alter_systemsettings_active_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        max_length=100, verbose_name="Palabra o Frase Clave"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "PALABRA CLAVE",
                "verbose_name_plural": "1. PALABRAS CLAVES",
            },
        ),
        migrations.CreateModel(
            name="MonitoredCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Comisión"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Monitorear Actividad"
                    ),
                ),
            ],
            options={
                "verbose_name": "COMISIÓN",
                "verbose_name_plural": "3. COMISIONES",
            },
        ),
        migrations.CreateModel(
            name="MonitoredMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sutra_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Medida (Ej: RC0011)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "MEDIDA a Rastrear",
                "verbose_name_plural": "2. MEDIDAS (Lista de Seguimiento)",
            },
        ),
        migrations.DeleteModel(
            name="SearchTerm",
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={},
        ),
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "verbose_name": "Estado del Sistema",
                "verbose_name_plural": "Estado del Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Configuración de Usuario",
                "verbose_name_plural": "Configuración de Usuarios",
            },
        ),
        migrations.RemoveField(
            model_name="bill",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="filing_date",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="is_alerted",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="active_days",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="high_freq_end",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="high_freq_interval",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="high_freq_start",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="low_freq_interval",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_alerts",
            field=models.BooleanField(
                default=False, verbose_name="Activar Alertas por Email"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID Chat Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="commission",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Comisión Asignada"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="number",
            field=models.CharField(max_length=50, verbose_name="Número Oficial"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                default="Radicado", max_length=100, verbose_name="Estado Actual"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="sutra_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="ID Medida"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Robot Encendido"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
