# Generated by Django 5.1.3 on 2026-01-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_keyword_monitoredcommission_monitoredmeasure_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemsettings",
            options={"verbose_name": "Estado del Sistema"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Canales de Discord",
                "verbose_name_plural": "Configuración de Canales Discord",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="discord_webhook",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email_alerts",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="telegram_chat_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_commissions",
            field=models.URLField(
                blank=True, null=True, verbose_name="🤖 Webhook Comisiones"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_keywords",
            field=models.URLField(
                blank=True, null=True, verbose_name="🤖 Webhook Palabras Claves"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_measures",
            field=models.URLField(
                blank=True, null=True, verbose_name="🤖 Webhook Medidas Específicas"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_news",
            field=models.URLField(
                blank=True, null=True, verbose_name="🤖 Webhook Noticias (Futuro)"
            ),
        ),
    ]
