# Generated by Django 5.2.10 on 2026-01-17 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_systemsettings_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="billevent",
            name="bill",
        ),
        migrations.DeleteModel(
            name="SystemSettings",
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={},
        ),
        migrations.AlterModelOptions(
            name="monitoredcommission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="monitoredmeasure",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="webhook_news",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_general",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Webhook General"
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="commission",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="sutra_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="sutra_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bill",
            name="title",
            field=models.TextField(default="Sin Titulo"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="keyword",
            name="term",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="monitoredcommission",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="monitoredcommission",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="monitoredmeasure",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="monitoredmeasure",
            name="sutra_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="webhook_commissions",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Webhook Comisiones"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="webhook_keywords",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Webhook Palabras Clave",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="webhook_measures",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Webhook Medidas Específicas",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.bill",
            ),
        ),
        migrations.DeleteModel(
            name="BillEvent",
        ),
    ]
