# Generated by Django 5.2.10 on 2026-01-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_newssource_remove_bill_commission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
