# Generated by Django 5.2.10 on 2026-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_newstopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
