# Generated by Django 5.2.10 on 2026-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_article_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("keywords", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="NewsTopic",
        ),
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
    ]
