# Generated by Django 5.2.10 on 2026-01-18 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_billversion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monitoredmeasure",
            old_name="created_at",
            new_name="added_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="monitoredcommission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="newspreset",
            name="created_at",
        ),
        migrations.AddField(
            model_name="billversion",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="bills_pdfs/"),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="Evento General", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(default="2024-01-01 00:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bill",
            name="number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(default="Radicado", max_length=100),
        ),
        migrations.AlterField(
            model_name="billversion",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="billversion",
            name="full_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="newspreset",
            name="keywords",
            field=models.TextField(help_text="Palabras separadas por coma"),
        ),
        migrations.AlterField(
            model_name="newspreset",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="newssource",
            name="icon_class",
            field=models.CharField(default="fas fa-rss", max_length=50),
        ),
    ]
