# Generated by Django 5.1.3 on 2026-01-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_article_options_remove_bill_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Activar/desactivar el servicio globalmente')),
                ('active_days', models.CharField(default='0,1,2,3,4', help_text='Días activos: 0=Lunes, 6=Domingo', max_length=50)),
                ('high_freq_start', models.TimeField(default='08:00', help_text='Inicio del horario intensivo')),
                ('high_freq_end', models.TimeField(default='17:00', help_text='Fin del horario intensivo')),
                ('high_freq_interval', models.IntegerField(default=15, help_text='Intervalo en modo intensivo (minutos)')),
                ('low_freq_interval', models.IntegerField(default=120, help_text='Intervalo en modo pasivo (minutos)')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
