# Generated by Django 5.1.3 on 2026-01-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_monitoredcommission_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_hash',
            field=models.CharField(blank=True, help_text='Hash MD5 del contenido', max_length=32, null=True),
        ),
    ]
