# Generated by Django 5.1.3 on 2026-01-23 04:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_hybrid_search_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector de embeddings semánticos (384 dimensiones)', null=True),
        ),
    ]
