# Generated by Django 5.1.3 on 2026-01-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_article_embedding'),
    ]

    operations = [        # Crear función de trigger para actualizar search_vector automáticamente
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION update_article_search_vector()
            RETURNS trigger AS $$
            BEGIN
                -- Actualizar search_vector con pesos diferenciados:
                -- A: título (máxima relevancia)
                -- B: snippet (contenido principal)
                -- C: ai_summary (resumen generado por IA)
                -- Usar diccionario español con unaccent para remover tildes
                NEW.search_vector := 
                    setweight(to_tsvector('spanish', unaccent(coalesce(NEW.title, ''))), 'A') ||
                    setweight(to_tsvector('spanish', unaccent(coalesce(NEW.snippet, ''))), 'B') ||
                    setweight(to_tsvector('spanish', unaccent(coalesce(NEW.ai_summary, ''))), 'C');
                
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS update_article_search_vector() CASCADE;"
        ),
        
        # Crear trigger que ejecuta la función BEFORE INSERT OR UPDATE
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER trigger_update_article_search_vector
            BEFORE INSERT OR UPDATE OF title, snippet, ai_summary
            ON core_article
            FOR EACH ROW
            EXECUTE FUNCTION update_article_search_vector();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS trigger_update_article_search_vector ON core_article;"
        ),
        
        # Actualizar registros existentes (si los hay)
        migrations.RunSQL(
            sql="""
            UPDATE core_article
            SET search_vector = 
                setweight(to_tsvector('spanish', unaccent(coalesce(title, ''))), 'A') ||
                setweight(to_tsvector('spanish', unaccent(coalesce(snippet, ''))), 'B') ||
                setweight(to_tsvector('spanish', unaccent(coalesce(ai_summary, ''))), 'C')
            WHERE search_vector IS NULL OR search_vector = '';
            """,
            reverse_sql=migrations.RunSQL.noop
        ),    ]
