# Generated by Django 5.1.3 on 2026-01-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_newspreset_search_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedding',
        ),
    ]
