# Generated by Django 5.1.3 on 2026-01-24 18:48

import datetime
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_monitoredcommission_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Configuración del Sistema'},
        ),
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Vector de embeddings semánticos (384 dimensiones)', null=True),
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='threshold',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='fields_to_analyze',
            field=models.CharField(default='title,description', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='threshold',
            field=models.IntegerField(default=15, help_text='Score mínimo de relevancia (0-100)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_days',
            field=models.CharField(default='0,1,2,3,4', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_interval',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='low_freq_interval',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_commissions',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_general',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_keywords',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_measures',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
