# Generated by Django 5.1.3 on 2026-01-25 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_systemsettings_options_article_embedding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuración del Sistema'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Palabras clave para filtrar medidas de esta comisión (separadas por coma)'),
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', help_text='Método de búsqueda para esta comisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredcommission',
            name='threshold',
            field=models.IntegerField(default=15, help_text='Score mínimo de relevancia (0-100)'),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Palabras clave para filtrar medidas relevantes (separadas por coma)'),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', help_text='Método de búsqueda para esta medida', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoredmeasure',
            name='threshold',
            field=models.IntegerField(default=15, help_text='Score mínimo de relevancia (0-100)'),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='fields_to_analyze',
            field=models.CharField(default='title,description', help_text='Campos a analizar separados por coma: title, description', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='search_method',
            field=models.CharField(choices=[('hybrid', 'Búsqueda Híbrida (RRF)'), ('semantic', 'Búsqueda Semántica (IA)'), ('keyword', 'Búsqueda por Palabras Clave')], default='hybrid', help_text='Método de búsqueda: híbrida (RRF), semántica (IA) o por palabras clave', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspreset',
            name='threshold',
            field=models.IntegerField(default=15, help_text='Score mínimo de relevancia (0-100) para incluir artículo. Recomendado: 15-20 para alta sensibilidad'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Días activos: 0=Lunes, 6=Domingo', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_end',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Fin del horario intensivo'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_interval',
            field=models.IntegerField(default=15, help_text='Intervalo en modo intensivo (minutos)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='high_freq_start',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Inicio del horario intensivo'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activar/desactivar el servicio globalmente'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='low_freq_interval',
            field=models.IntegerField(default=120, help_text='Intervalo en modo pasivo (minutos)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_commissions',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Webhook Comisiones'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_general',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Webhook General'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_keywords',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Webhook Keywords'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='webhook_measures',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Webhook Medidas'),
        ),
    ]
